name: dart_backend_two
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_modular: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
